### ISSUE TITLE
Calendar entries being re-created

### ISSUE THREAD

**Issue by neildhunter** [jampez77/DVLA-Vehicle-Enquiry-Service#23]
After updating the integration and restarting HA it looks like it creates calendar entries even if they already exist. After today's update I now have 3 duplicate MOT events for the same vehicle on the same date...

**Comment by jampez77** [comment]
Hey, thanks for taking the time to log this issue.

I've witnessed this issue myself and currently unsure exactly how to handle it. This issue is that I can't access the Unique id of created calendar entities as a check to see if they have been created previously.

My only advice now, is delete the duplicates by hand and re-install the integration.  You shouldn't need to restart HA. In theory it shouldn't duplicate them when you restart. I'll keep this open so I can continue to look into it.

**Comment by neildhunter** [comment]
Thanks for the reply - I don't know whether it does it on just a restart as I've noticed it after updating needing a restart! I'll keep an eye on it and just keep deleting the duplicates for now - it looks like you've got some code in place to try to avoid creating ones that already exist. I might have to poke around when I have time to see why that isn't spotting them.

**Comment by si458** [comment]
im noticing a similar issue as i wanted to change calendar but it never created the event on a different calendar
instead all im getting is errors about api key in the logs
```
2024-11-05 16:56:27.078 INFO (MainThread) [homeassistant.components.binary_sensor] Setting up dvla.binary_sensor
2024-11-05 16:56:27.078 ERROR (MainThread) [homeassistant.components.binary_sensor] Error while setting up dvla platform for binary_sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 361, in _async_setup_platform
    await asyncio.shield(awaitable)
  File "/config/custom_components/dvla/binary_sensor.py", line 53, in async_setup_entry
    coordinator = DVLACoordinator(hass, session, entry.data)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/dvla/coordinator.py", line 32, in __init__
    self.api_key = data[CONF_API_KEY]
                   ~~~~^^^^^^^^^^^^^^
KeyError: 'api_key'
2024-11-05 16:56:27.086 INFO (MainThread) [homeassistant.components.calendar] Setting up dvla.calendar
```
